data_path: data/sources.hdf5
model_path: code/nlnmm.stan
results_path: results/{unique_hash}/results.hdf5

multiprocessing: true
processes: 20
check_finite: true
suppress_stan_output: true
random_seed: 0
number_of_sources_for_gaussian_process: 10000
number_of_science_sources: 100000
number_of_probability_draws: 100

plot_mixture_model_figures: false
ignore_keywords_when_creating_hash:
  - ignore_keywords_when_creating_hash
  - plot_mixture_model_figures
  - gp_initial_guesses

data_bounds:
  bp_rp: [-0.5, 5]
  absolute_g_mag: [-15, 12]
  phot_g_mean_mag: [3, 15]

models:
  ast:
    kdtree_label_names: [bp_rp, absolute_g_mag, phot_g_mean_mag]
    kdtree_maximum_points: 1024
    kdtree_maximum_radius: [0.5, 1, 1]
    kdtree_minimum_points: 128
    kdtree_minimum_radius: [0.1, 0.1, 0.1]
    kdtree_relative_scales: [0.05, 0.5, 0.5]
    predictor_label_name: ruwe
    bounds:
      theta: [0.5, 1.1]
      mu_single: [0.5, 5]
      sigma_single: [0.025, 1]
      sigma_multiple: [0.1, 2]
    tol_sum_sigma: 10
    tol_proximity: 0.01
  rv:
    kdtree_label_names: [bp_rp, absolute_rp_mag, phot_rp_mean_mag]
    kdtree_maximum_points: 1024
    kdtree_maximum_radius: [0.5, 1, 1]
    kdtree_minimum_points: 128
    kdtree_minimum_radius: [0.1, 0.1, 0.1]
    kdtree_relative_scales: [0.05, 0.5, 0.5]
    predictor_label_name: rv_jitter
    bounds:
      theta: [0.5, 1.1]
      mu_single: [0.05, 5]
      sigma_single: [0.025, 5]
      sigma_multiple: [0.2, 1.6]
    tol_sum_sigma: 10
    tol_proximity: 0.01

gp_initial_guesses:
  ast:
    mu_single: [2.11952289, -8.11510261, -1.76705322,  0.66798723, -1.41052901]
    sigma_single: [0.25855645, -8.2251049 , -1.45272654,  1.18873635, -2.33497652]
    mu_multiple:  [5.11043008,  5.15561675,  9.13884006,  2.49112459, 13.16006721]
    sigma_multiple: [0.47961741, -4.33031589, -2.19776114,  0.94046639,  1.08231821]
  rv:
    mu_single: [0.70799748, -7.11288233, -3.07209803,  1.51100918,  2.56365552]
    sigma_single: [0.6010562, -7.78274635, -2.40511388,  1.85969737,  3.69525254]
    mu_multiple: [0.1869771, -3.65507317, -2.80520958,  0.95649974,  1.1112062 ]
    sigma_multiple: [0.47922389, -6.8655726 , -2.76490369,  0.81800791,  0.83875105]



gaia_archive_adql_calibration_query: >
  SELECT *,
         phot_g_mean_mag + 5 * log10(parallax/100) 
            AS absolute_g_mag,
         phot_bp_mean_mag + 5 * log10(parallax/100) 
            AS absolute_bp_mag,
         phot_rp_mean_mag + 5 * log10(parallax/100) 
            AS absolute_rp_mag,
         sqrt(astrometric_chi2_al/(astrometric_n_good_obs_al - 5)) 
            AS ruwe,
         sqrt(rv_nb_transits * 3.14/2 * power(radial_velocity_error, 2)) 
            AS rv_jitter
  FROM  gaiadr2.gaia_source
  WHERE duplicated_source = 'false'
    AND radial_velocity > -9999
    AND bp_rp > -9999
    AND phot_g_mean_mag < 13
    AND parallax > 0
    AND parallax_over_error > 5